import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Provider } from '@/components/ui/provider'
import { Box, Grid, GridItem } from '@chakra-ui/react'
import { Toaster } from "@/components/ui/toaster"
import { Header } from '@/components/Header'
import { PlanProvider } from './providers/usePlan'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import { ReactQueryProvider } from './providers/ReactQueryProvider'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <ReactQueryProvider>
            <Provider>
              <PlanProvider>
                <Box margin="0 2rem">
                  <Grid templateRows="1fr auto" height="100vh">
                    <GridItem><Header /></GridItem>
                    <GridItem height="90vh">{children}</GridItem>
                  </Grid>
                  <Toaster />
                </Box>
              </PlanProvider>
            </Provider>
          </ReactQueryProvider>
        </UserProvider>
      </body>
    </html>
  )
}
