import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Provider } from '@/components/ui/provider'
import { Box, Grid, GridItem } from '@chakra-ui/react'
import { Header } from '@/components/Header'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import { ReactQueryProvider } from './providers/ReactQueryProvider'
import { PlanProvider } from '@/app/providers/usePlanContext'
import { Extra } from '@/components/Extra'
import { AccountProvider } from '@/app/providers/useAccountContext'
import { Toaster } from '@/components/ui/toaster'
import PlanLayout from '@/app/layout/PlanLayout'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <ReactQueryProvider>
            <Provider>
              <AccountProvider>
                <PlanProvider>
                  <PlanLayout>
                    <Box margin="0 2rem">
                      <Grid templateRows="10% auto" height="100vh">
                        <GridItem><Header /></GridItem>
                        <GridItem overflow="auto">{children}</GridItem>
                      </Grid>
                    </Box>
                  </PlanLayout>
                </PlanProvider>
                <Extra />
              </AccountProvider>
              <Toaster />
            </Provider>
          </ReactQueryProvider>
        </UserProvider>
      </body>
    </html>
  )
}
